apiVersion: apps/v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
    - targetPort: 80 # if we don't provide a targetPort it will assigned as port
      port: 8080
      nodePort: 30008 # if nodePort is not provided, it will assign any free port inside valide range (30000 - 32767)
  selector:
    type: server
  